### ISSUE TITLE
deploy script not working

### ISSUE THREAD

**Issue by iankressin** [Mean-Finance/dca-v2-core#219]
After installing the dependencies using `yarn` and running the tests as mentioned in the README, I tried to deploy the contracts using `yarn deploy` but node vm's throw the followig error:

```
dca-v2-core/node_modules/@mean-finance/deterministic-factory/utils/deployment.ts:1
import hre, { ethers } from 'hardhat';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Node version being used is 16.15.1. but also tried with 16.13.2 and got the same results

I also tried to clone `@mean-finance/deterministic-factory`, add `"type": "module"` to `package.json` and install it locally to this project, but end up with the same results

I wonder which versions are you guys using in your environment to make the deploy script run

**Comment by nchamo** [comment]
Hey @iankressin !

We had the same problem with typechain, and we had quite a few options:
1. Transpile typechain
2. Re-generate it everywhere
3. Run it like this: `TS_NODE_SKIP_IGNORE=true yarn deploy`

We went with option 3, since it was the quickest solution

Also, I'll close https://github.com/Mean-Finance/deterministic-factory/issues/5 so we can keep the discussion here, if that's ok with you

**Comment by iankressin** [comment]
I went with the 3rd option and it works, thanks!
